alias agfr='/home/lachmansinghet/ADFRsuite-1.0/bin/agfr'
alias adfr='/home/lachmansinghet/ADFRsuite-1.0/bin/adfr'
alias agfrgui='/home/lachmansinghet/ADFRsuite-1.0/bin/agfrgui'
alias autosite='/home/lachmansinghet/ADFRsuite-1.0/bin/autosite'
alias about='/home/lachmansinghet/ADFRsuite-1.0/bin/about'
alias prepare_receptor='/home/lachmansinghet/ADFRsuite-1.0/bin/prepare_receptor'
alias prepare_ligand='/home/lachmansinghet/ADFRsuite-1.0/bin/prepare_ligand'
alias pythonsh='/home/lachmansinghet/ADFRsuite-1.0/bin/pythonsh'
